### ISSUE TITLE
Support for .gifs

### ISSUE THREAD

**Issue by shivan-s** [boidolr/pre-commit-images#117]
Hi there,

I think this is a fantastic pre-commit hook. Thank you for your hard work. I use it for my statically generated blog.

My question is: is it possible to support .gif file compression?

Thank you in advance and looking forward to any conversation.

**Comment by boidolr** [comment]
Hi @shivan-s,

Pillow does offer an option to optimize, though it will only reduce the palette, and only if it can reduce it by at least half: https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#gif-saving
I am unsure if that would usually be enough to result in an actual reduction. Would such an optimization make any difference in your use case? What happens when you apply `Pillow` to the kind of GIFs that you use?

**Comment by boidolr** [comment]
Turns out I can support that with the code I already have, so you can try it out:
```
repos:
    - repo: https://github.com/boidolr/pre-commit-images
      rev: be4690a3ea46fe3939287d1b80cd77384eaf9acd
      hooks:
      - id: optimize-gif
```

**Comment by shivan-s** [comment]
Hey @boidolr,

Thanks for getting back to me. If you are interested in my specific use case, I have a blog where I sometimes use gifs as the "image".

https://github.com/boidolr/pre-commit-images/assets/51132467/aef2229b-3153-4a36-91c2-159892a856ca

I did run the optimisation:

```
optimize gifs............................................................Failed
- hook id: optimize-gif
- files were modified by this hook

Optimized content/posts/programming/named-anchors/named-anchors.gif by 2.16Mb of 2.23Mb (96.96%)
Optimized content/posts/programming/bounding-user-input/bound.gif by 2.47Mb of 2.60Mb (94.89%)
Optimized content/posts/programming/rankings/ranking.gif by 6.10Mb of 6.25Mb (97.58%)
Optimized content/posts/programming/screencasts-to-gifs/example.gif by 4.79Mb of 4.86Mb (98.44%)
```

But you are right, they get reduced into a single non-animated pallet, which is not what I am going for but may be useful in other use cases.

I can see that to get gif optimisation to keep the animation requires other dependencies (non-python like [gifsicle](https://www.lcdf.org/gifsicle/)). I can understand if this feature request gets shelved.

Thank you again for your time in considering this issue.

**Comment by boidolr** [comment]
Hi @shivan-s thanks for following up and providing an example.

As I have not found a wrapper for `gifsicle` or similar that will be reliably installed on every environment I do not want to support GIFs at this time. Pillow by itself does not offer a lot for this particular use case.

As a workaround, you could always use `gifsicle` by installing it yourself and using a system hook:
```
- repo: local
  hooks:
  - id: gifsicle
    entry: gifsicle -O3 -i --batch
    language: system
    types: [gif]
```

Thanks for rising this issue.
