### ISSUE TITLE
Bug: Optimize svgs fails on windows due to non-utf-8 encoding 

### ISSUE THREAD

**Issue by FredHappyface** [boidolr/pre-commit-images#3]
Hi thanks for this tool! Having an image compression utility to add to my ever expanding pre-commit file makes for a great replacement to some of the cloud based solutions 

## Background
I have spotted a small bug however, on windows (happy to open a pr). The `read_text` and `write_text` functions need `encoding="utf-8"` as the default encoding on windows differs to other os' (not sure why that is)

## Details 
For the https://github.com/FHPythonUtils/FHPrint repo

```
Optimize svgs............................................................Failed
- hook id: optimize-svg
- exit code: 1

Failed optimization for readme-assets/screenshots/screenshot-0.svg ('charmap' codec can't decode byte 0x90 in position 4659: character maps to <undefined>)
```

## Solution 

The `read_text` and `write_text` functions need `encoding="utf-8"` as the default encoding on windows differs to other os' (not sure why that is)

Thank you for your time :)

**Comment by FredHappyface** [comment]
Cheers :)

**Comment by boidolr** [comment]
Glad you find it useful - I've added the encoding and bumped the version.
